import { clipboard } from 'electron'
import { createHash } from 'crypto'
import { basename } from 'path'
import * as store from './store'
import * as blobs from './blob-store'
import { consumeSuppression } from './clipboard-writer'
import { hasFileClip, rawFileFingerprint, readFilePaths } from './pasteboard-files'
import { getSettings } from './settings'
import { extractAppIcon, getFrontmostApp, type FrontApp } from './frontmost-app'

// Password managers and similar mark items with these types — never capture.
const SKIP_TYPES = [
  'org.nspasteboard.TransientType',
  'org.nspasteboard.ConcealedType',
  'org.nspasteboard.AutoGeneratedType',
  'de.petermaurer.TransientPasteboardType',
  'com.typeit4me.clipping',
  'Pasteboard generator type',
  'com.agilebits.onepassword'
]

const TICK_MS = 400

type Kind = 'files' | 'text' | 'image' | 'none'

let lastFp = ''
let timer: ReturnType<typeof setInterval> | null = null
let onChange: () => void = () => {}

const sha1 = (b: Buffer | string): string => createHash('sha1').update(b).digest('hex')

function safeHas(format: string): boolean {
  try {
    return clipboard.has(format)
  } catch {
    return false
  }
}

// Cheap-to-expensive ladder: formats → skip-types → files → text → image header.
function fingerprint(): { fp: string; kind: Kind } {
  const formats = clipboard.availableFormats()
  if (formats.length === 0) return { fp: 'empty', kind: 'none' }
  if (SKIP_TYPES.some(safeHas)) return { fp: 'skip:' + Date.now(), kind: 'none' }
  if (hasFileClip()) {
    const raw = rawFileFingerprint()
    if (raw) return { fp: 'files:' + sha1(raw), kind: 'files' }
  }
  const text = clipboard.readText()
  if (text) return { fp: 'text:' + sha1(text), kind: 'text' }
  if (formats.some((f) => f.startsWith('image/'))) {
    const buf = clipboard.readBuffer('public.tiff')
    if (buf.length > 0) {
      return { fp: `img:${buf.length}:` + sha1(buf.subarray(0, 8192)), kind: 'image' }
    }
  }
  return { fp: 'other:' + formats.join(','), kind: 'none' }
}

function textHash(text: string): string {
  return sha1('text:' + text)
}

function filesHash(paths: string[]): string {
  return sha1('files:' + paths.join('\n'))
}

function buildClip(kind: Exclude<Kind, 'none'>): store.NewClip | null {
  if (kind === 'files') {
    const paths = readFilePaths()
    if (paths.length === 0) return null
    const names = paths.map((p) => basename(p))
    const preview =
      paths.length === 1
        ? names[0]
        : `${paths.length} files: ${names.slice(0, 3).join(', ')}${names.length > 3 ? '…' : ''}`
    return { type: 'files', hash: filesHash(paths), preview, filePaths: paths, byteSize: 0 }
  }
  if (kind === 'text') {
    const text = clipboard.readText()
    if (!text.trim()) return null
    let html: string | undefined
    try {
      const h = clipboard.readHTML()
      if (h && h.length <= 512 * 1024) html = h
    } catch {
      // plain text only
    }
    const preview = text.replace(/\s+/g, ' ').trim().slice(0, 200)
    return {
      type: 'text',
      hash: textHash(text),
      preview,
      textContent: text,
      htmlContent: html,
      byteSize: Buffer.byteLength(text)
    }
  }
  const img = clipboard.readImage()
  if (img.isEmpty()) return null
  const png = img.toPNG()
  const hash = sha1(png)
  const { width, height } = img.getSize()
  const { imagePath, thumbPath } = blobs.saveImage(hash, png, img)
  return {
    type: 'image',
    hash,
    preview: `Image ${width}×${height}`,
    imagePath,
    thumbPath,
    imageW: width,
    imageH: height,
    byteSize: png.length
  }
}

async function cacheAppIcon(front: FrontApp): Promise<void> {
  if (store.getAppIcon(front.bundleId)) return
  const file = `appicon-${front.bundleId.replace(/[^a-zA-Z0-9.-]/g, '_')}.png`
  if (await extractAppIcon(front.path, blobs.resolveBlob(file))) {
    store.upsertAppIcon(front.bundleId, front.name, file)
  }
}

async function capture(kind: Exclude<Kind, 'none'>): Promise<void> {
  // Self-write? Verify by hash for text/files (cheap); by type for images
  // (avoids re-encoding a large PNG just to confirm what we already know).
  const suppressedId = consumeSuppression()
  if (suppressedId != null) {
    const row = store.getItem(suppressedId)
    if (row) {
      const matches =
        kind === 'image'
          ? row.type === 'image'
          : kind === 'text'
            ? row.type === 'text' && row.hash === textHash(clipboard.readText())
            : row.type === 'files' && row.hash === filesHash(readFilePaths())
      if (matches) {
        store.bumpToTop(suppressedId)
        onChange()
        return
      }
    }
  }

  const clip = buildClip(kind)
  if (!clip) return
  const front = await getFrontmostApp()
  if (front) {
    clip.sourceApp = front.bundleId
    clip.sourceAppName = front.name
    await cacheAppIcon(front)
  }
  store.insertOrBump(clip)
  blobs.gcBlobs(store.evict(getSettings().historyCap))
  onChange()
}

let capturing = false

function tick(): void {
  try {
    const { fp, kind } = fingerprint()
    if (fp === lastFp) return
    if (capturing) return // re-check this fp next tick once the in-flight capture lands
    lastFp = fp
    if (kind === 'none') return
    capturing = true
    void capture(kind)
      .catch((err) => console.error('[clipboard-watcher]', err))
      .finally(() => {
        capturing = false
      })
  } catch (err) {
    console.error('[clipboard-watcher]', err)
  }
}

export function startWatcher(cb: () => void): void {
  onChange = cb
  try {
    lastFp = fingerprint().fp // don't re-capture whatever was on the clipboard pre-launch
  } catch {
    lastFp = ''
  }
  timer = setInterval(tick, TICK_MS)
}

export function stopWatcher(): void {
  if (timer) clearInterval(timer)
  timer = null
}
